#!/usr/bin/env bash
ls_bin=ls
if [ -x "$(command -v lsd)" ]; then
  ls_bin=lsd
fi


# Some shortcuts for different directory listings
alias dir=$ls_bin' -lhcF' # classify files in colour
alias ls='$ls_bin' # lsd is compatiable with ls
alias ll=$ls_bin' -l' # long list
alias la=$ls_bin' -la' # all but . and ..
alias l=$ls_bin' -lt' # time sort list
alias lt='$ls_bin --tree' # directory tree

alias cdls='dirs -v'
# git with global aliases in config
alias g='git'
# exit quick
alias q='exit'

# Default to human readable figures
alias df='df -h'
alias du='du -h'
alias grep='grep --color'                     # show differences in colour

# Make file transfers verbose
alias mv='mv -v'
alias cp='cp -v'
alias mkdir='mkdir -v'
alias rm='rm -v'

# Remove directory
alias rmd='rm -r'

# Get week number
alias week='date +%V'

# Stopwatch
alias timer='echo "Timer started. Stop with Ctrl-D." && date && time cat && date'

# Generate terminal utf-8 qrcode
alias qrcode='qrencode -t UTF8 -o -'

# IP addresses
alias ip="dig +short myip.opendns.com @resolver1.opendns.com"
alias localip="ipconfig getifaddr en0"
alias ips="ifconfig -a | grep -o 'inet6\? \(addr:\)\?\s\?\(\(\([0-9]\+\.\)\{3\}[0-9]\+\)\|[a-fA-F0-9:]\+\)' | awk '{ sub(/inet6? (addr:)? ?/, \"\"); print }'"

# View HTTP traffic
alias sniff="sudo ngrep -d 'en1' -t '^(GET|POST) ' 'tcp and port 80'"
alias httpdump="sudo tcpdump -i en1 -n -s 0 -w - | grep -a -o -E \"Host\: .*|GET \/.*\""

# Print each PATH entry on a separate line
alias path='echo -e ${PATH//:/\\n}'

# kicad hide references
alias kicad_hide="sed -i -E g/(fp_text reference...*)...*...)$/ s/$/ hide/g"

if [[ $OSTYPE =~ "darwin" ]]; then
  # Merge PDF files
  # Usage: `mergepdf -o output.pdf input{1,2,3}.pdf`
  alias mergepdf='/System/Library/Automator/Combine\ PDF\ Pages.action/Contents/Resources/join.py'

  # Airport CLI alias
  alias airport='/System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport'

  # Lock the screen (when going AFK)
  alias afk="/System/Library/CoreServices/Menu\ Extras/User.menu/Contents/Resources/CGSession -suspend"

  # Open Finder window of current path
  alias finder='open .'

  # Open gvim from term
  alias gvim='/Applications/MacVim.app/Contents/MacOS/Vim -g'

  # load/unload ktext
  alias ftx_load='sudo kextload -b com.apple.driver.AppleUSBFTDI'
  alias ftx_unload='sudo kextunload -b com.apple.driver.AppleUSBFTDI'
  alias nosleep='pmset noidle'

  alias update='brew upgrade && brew update'
  alias speedtest-macos='networkQuality'
  alias fit2csv='java -jar ~/FitSDKRelease/java/FitCSVTool.jar'
  # lsusb compat mode
  alias lsusb='cyme --lsusb'
else
  alias reboot="sudo systemctl reboot"
  alias poweroff="sudo systemctl poweroff"
  alias halt="sudo systemctl halt"
fi

# ESP32
alias env_esp32='export PATH="$ESP_TOOLCHAIN_PATH:$PATH"'

# Flutter
alias env_flutter='export PATH="$PATH:$HOME/flutter/flutter/bin"'
