#!/usr/bin/env bash

# User settings
export VISUAL=vim
export EDITOR=vim

# Colourful vim
export TERM='xterm-256color'

if [[ $OSTYPE =~ "darwin" ]]; then
  export PATH="$PATH:/usr/local/sbin:/Applications/MATLAB_R2014b.app/bin/maci64"

  # Arduino-mk
  export ARDUINO_DIR=/Applications/Arduino.app/Contents/Java 
  export ARDMK_DIR=/usr/local/Cellar/arduino-mk/1.5.2
  export AVR_TOOLS_DIR=/usr/local
else
  export ARDUINO_DIR=C:/Arduino
  export ARDMK_DIR=C:/Arduino-Makefile
  export ARDUINO_SKETCHBOOK=C:/Users/John.Whittington/Documents/Arduino
fi
