#!/usr/bin/env bash

# User settings
if [ -x "$(command -v nvim)" ]; then
  export VISUAL=nvim
  export EDITOR=nvim
else
  export VISUAL=vim
  export EDITOR=vim
fi
export FZF_DEFAULT_COMMAND='fd --type f'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
# export PIPENV_VENV_IN_PROJECT=1 
export HISTFILE=~/.zsh_history
export HISTCONTROL=ignoreboth:erasedups:ignorespace
export HISTIGNORE="pass*:bw*:subkey*:*password*"
export HISTORY_IGNORE="(pass|bw|subkey)"
export HISTSIZE=20000
export SAVEHIST=$HISTSIZE

# Language
if [ -z $LANG ]; then
  export LANG="en_GB.UTF-8"
  export LC_COLLATE="C"
  export LC_CTYPE="UTF-8"
  export LC_MESSAGES="C"
  export LC_MONETARY="C"
  export LC_NUMERIC="C"
  export LC_TIME="C"
  export LC_ALL=$LANG
  export ITRAN=true
fi

# Colourful vim
if [[ $TERM == xterm-kitty ]]; then
  export TERM=xterm-256color
fi

export TERM='xterm-256color'

# Toolchain paths
export GOPATH="$HOME/go"
export PYENV_ROOT="$HOME/.pyenv"

# Cargo targets in global folder outside of project
export CARGO_TARGET_DIR="$HOME/.cargo/target"

if [[ $OSTYPE =~ "darwin" ]]; then
  # homebrew
  export HOMEBREW_NO_ENV_HINTS=1
  export HOMEBREW_NO_ANALYTICS=1

  export DROPBOX_ROOT=/Users/john/Library/CloudStorage/Dropbox
  export NOTE_DIR=$DROPBOX_ROOT/Files/notes
  export JOURNAL_DIR=~/Dropbox/Files/blogs/memoirs-of-a-john/_posts
  # match Linux path so it works with normal tools and kopia
  export RCLONE_CONFIG=/Users/john/.config/rclone/rclone.conf

  # Arduino-mk
  export ARDUINO_DIR=/Applications/Arduino.app/Contents/Java 
  export ARDMK_DIR=/usr/local/opt/arduino-mk
  export AVR_TOOLS_DIR=/usr/local
  export USER_LIB_PATH=~/Dropbox/Programming/Arduino/libraries

  # ESP32
  export ESP_TOOLCHAIN_PATH=~/esp/xtensa-esp32-elf/bin
  export IDF_PATH=~/esp/esp-idf
  export NNN_BMS='p:~/Dropbox/Projects/;m:/Users/john/Library/Preferences/.config/nnn/mounts;n:~/Dropbox/Files/notes'

  # ruby env
  export RUBY_CONFIGURE_OPTS="--with-openssl-dir=$HOMEBREW_PREFIX"

  # for fastlane
  export FLUTTER_ROOT='/Users/john/flutter/'

  # kicad makefile
  export KICADMK_DIR=/Users/john/git/kicad-makefile

  # homebrew libs for Cargo
  export LIBRARY_PATH="$LIBRARY_PATH:$HOMEBREW_PREFIX/lib"
else
  export NOTE_DIR=~/.notes

  # Arduino-mk
  export ARDUINO_DIR=/usr/share/arduino
  export ARDMK_DIR=/home/john/Arduino-Makefile
  export USER_LIB_PATH=/home/john/libraries

  # ESP32
  export ESP_TOOLCHAIN_PATH=/opt/esp/xtensa-esp32-elf/bin
  export IDF_PATH=/opt/esp/esp-idf
  # export PATH="$HOME/esp/xtensa-esp32-elf/bin:$PATH" # set using get_esp32 alias

  # ssh-agent started by systemd service on arch - replaced with `keychain`
  # export SSH_AUTH_SOCK="$XDG_RUNTIME_DIR/ssh-agent.socket"
fi

export TODO=$NOTE_DIR/todo.md

# nnn
export NNN_PLUG='o:fzopen;c:fzcd;d:diffs;'
export NNN_TRASH=1
export NNN_COLORS='4231'

# tmuxinator
export TMUXINATOR_CONFIG="$HOME/.config/tmuxinator"
