#!/usr/bin/bash

function cmd {
  cmd.exe /c "$@" 
}

function cdwsl {
  local win_path
  win_path=$(wslpath "$@")
  cd $win_path;
}

function embuild {
  /mnt/c/Program\ Files/SEGGER/SEGGER\ Embedded\ Studio\ for\ ARM\ 5.40c/bin/emBuild.exe $@
}
