# Setup $PATH https://gist.github.com/Linerre/f11ad4a6a934dcf01ee8415c9457e7b2
# Use homebrew python : homebrew bin : rust : ruby : : go
export PATH="/usr/local/opt/python/libexec/bin:$HOME/bin:/usr/local/bin:$HOME/.cargo/bin:/usr/local/opt/ruby/bin:/usr/local/sbin:$HOME/go/bin:$PATH"
