export LANG="en_GB.UTF-8"
export LC_COLLATE="C"
export LC_CTYPE="UTF-8"
export LC_MESSAGES="C"
export LC_MONETARY="C"
export LC_NUMERIC="C"
export LC_TIME="C"
export LC_ALL=$LANG

# p10k instant prompt
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Base16 Shell
# BASE16_SHELL="$HOME/.config/base16-shell/"
# [ -n "$PS1" ] && \
#     [ -z $SSH_CONNECTION ] && \
#     [ -s "$BASE16_SHELL/profile_helper.sh" ] && \
#         eval "$("$BASE16_SHELL/profile_helper.sh")"

if [[ -z $RELOADING ]]; then
  source $HOME/dotfiles/antigen/antigen.zsh
  source ~/.antigenrc
  antigen init ~/.antigenrc
  export ANTIGENRC_LOADED=true
fi

# bind UP and DOWN arrow keys
zmodload zsh/terminfo
# bind k and j for VI mode
bindkey -M vicmd 'k' history-substring-search-up
bindkey -M vicmd 'j' history-substring-search-down
# use the vi navigation keys in menu completion
bindkey '^n' expand-or-complete
bindkey '^p' reverse-menu-complete
bindkey '^k' history-substring-search-up
bindkey '^j' history-substring-search-down
bindkey '^h' backward-delete-char
bindkey '^w' backward-kill-word
bindkey '^e' forward-word
bindkey '^l' forward-char
# edit line
autoload -z edit-command-line
zle -N edit-command-line
bindkey "^x^e" edit-command-line
bindkey -M vicmd " " edit-command-line

# bash complete
autoload bashcompinit
bashcompinit

#========
# OPTS
#========

# don't save duplicate commands
setopt HIST_SAVE_NO_DUPS
# don't verify history expansions (can just do it with tab)
setopt NO_HIST_VERIFY
setopt HIST_EXPIRE_DUPS_FIRST
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_IGNORE_SPACE
setopt HIST_FIND_NO_DUPS
setopt HIST_SAVE_NO_DUPS

#========
# ALIASES
#========

alias reload="RELOADING=true source ~/.zshrc"

source ~/.aliases

#========
# EXPORTS
#========

source ~/.exports
source ~/.secrets
export KEYTIMEOUT=1
if [[ $WSL ]]; then
  source ~/.wsl
fi
# disable man highlight https://github.com/zdharma/fast-syntax-highlighting/issues/135
export FAST_HIGHLIGHT[whatis_chroma_type]=0

#========
# PROMPT
#========

[[ $TERM == *256color || $TERM == xterm* ]] || : ${PURE_POWER_MODE:=portable}
# source machine prompt if there is one, otherwise use my default
[ -f ~/.prompt.zsh ] && source ~/.prompt.zsh || source $HOME/dotfiles/support/prompt.zsh

#========
# FUNCTIONS
#========

source ~/.functions

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
[ -f ~/dotfiles/support/bindings.zsh ] && source ~/dotfiles/support/bindings.zsh

if type brew &>/dev/null; then
  FPATH=$(brew --prefix)/share/zsh/site-functions:$FPATH
fi

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# ruby env
eval "$(rbenv init -)"
# if command -v tmux &> /dev/null && [ -n "$PS1" ] && [[ ! "$TERM" =~ screen ]] && [[ ! "$TERM" =~ tmux ]] && [ -z "$TMUX" ]; then
#   exec tmux new-session -A -s main
# fi
