source $HOME/dotfiles/antigen/antigen.zsh

# Base16 Shell
BASE16_SHELL="$HOME/.config/base16-shell/"
[ -n "$PS1" ] && \
    [ -s "$BASE16_SHELL/profile_helper.sh" ] && \
        eval "$("$BASE16_SHELL/profile_helper.sh")"

source ~/.antigenrc
antigen init ~/.antigenrc

# bind UP and DOWN arrow keys
zmodload zsh/terminfo
bindkey "$terminfo[kcuu1]" history-substring-search-up
bindkey "$terminfo[kcud1]" history-substring-search-down
# bind k and j for VI mode
bindkey -M vicmd 'k' history-substring-search-up
bindkey -M vicmd 'j' history-substring-search-down

# bash complete
autoload bashcompinit
bashcompinit

#========
# OPTS
#========

# don't save duplicate commands
setopt HIST_SAVE_NO_DUPS
# don't verify history expansions (can just do it with tab)
setopt NO_HIST_VERIFY

#========
# ALIASES
#========

alias reload="~/.zshrc"

source ~/.aliases

#========
# EXPORTS
#========

source ~/.exports
source ~/.secrets
export KEYTIMEOUT=1

#========
# FUNCTIONS
#========

source ~/.functions

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
